apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kushagraag/java-app-frontend
        ports:
        - containerPort: 3000  # Updated to match the port your app is listening on
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: frontend-storage
          mountPath: /data
      volumes:
      - name: config-volume
        configMap:
          name: java-app-config
      - name: frontend-storage
        persistentVolumeClaim:
          claimName: frontend-pvc

